[package]
name = "shelve"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
rocket = "0.5.0-rc.1"
priority-queue = "1"
hyper = "0.14"
dotenv = "0.15"
err-derive = "0.3"
rand = "0.8"
uuid = { version = "0.8", features = ["serde", "v4"] }
rust-embed = "5"
serde = "1"
serde_json = "1"
multipart = "0.18"
async-trait = "0.1"
futures-util = { version = "0.3" }